---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 716006753993945088-jlByhrGU458D3CstZSGj9lIH9UR1qpm
:access_token_secret: F8b8eNOCpASbh7DOax5zFoIkITheNhwBbs1KJ3NcV2od3
